### ISSUE TITLE
other photo

### ISSUE THREAD

**Issue by chandlergis** [wildoctopus/huggingface-cloth-segmentation#1]
When I run other images locally, it seems to process out the same default few images

**Comment by wildoctopus** [comment]
Hi @chandlergis ,  If you are using "process.py" script to proces locally, then you need to pass the path for "image" arg. So do check your path once. And if you are using gradio script, then you dont need to worry for setting up path. Just upload image from the interface, it will work. 

If you have modified the script then do cehck the paths and for convinence you can share the code here as well. I an take a look.

**Comment by chandlergis** [comment]
Thank you, I just tested that some other images were working and then some of them were of questionable quality causing me to make this error in judgement thinking I was just dealing with the default image
