### ISSUE TITLE
The new clothing styles cannot be recognized.

### ISSUE THREAD

**Issue by prog-ape** [wildoctopus/huggingface-cloth-segmentation#2]
The new clothing styles cannot be recognized，What is the solution? Is it to retrain the model?

**Comment by wildoctopus** [comment]
> The new clothing styles cannot be recognized，What is the solution? Is it to retrain the model?

HI @prog-ape ,

The model is trained for imaterialist-fashion-2019-FGVC6 dataset. So if you are using a diffet style then you need to retrain your model.
